networks:
  database: {}
services:
  image:
    container_name: image
    depends_on:
    - mysql
    environment:
      APP_URL: http://localhost:3333
      COOKIE_SECURE_OFF: "yes"
      DB_HOST: mysql
      DB_NAME: image
      DB_PASSWORD: xxxxxxx
      DB_USER: root
      ENVIRONMENT: development
      FIRST_IMAGE_API_ACCESS_TOKEN: xxxxxx
      PORT_API: '3333'
      PORT_IMAGE_SERVER: '7777'
    image: openstad/image
    networks:
      database: null
    ports:
    - 80:3333/tcp
    restart: always
    volumes:
    - /Users/toshkoevoets/Documents/code/openstad-app/image/images:/app/images:rw
  mysql:
    entrypoint: sh -c " echo 'CREATE DATABASE IF NOT EXISTS auth; CREATE DATABASE
      IF NOT EXISTS image; CREATE DATABASE IF NOT EXISTS api;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: dummy
      MYSQL_PASSWORD: xxxxxxx
      MYSQL_ROOT_PASSWORD: xxxxxxx
    expose:
    - '3306'
    - '33060'
    image: mysql:5
    networks:
      database: null
    ports:
    - 3310:3306/tcp
    restart: unless-stopped
    volumes:
    - database:/var/lib/mysql:rw
version: '3.1'
volumes:
  database: {}

